environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - node --version
  - npm --version

test_script:
  - npm run lint
  - node az-iot-diag.js -h
  - node az-iot-diag.js set -h